{
 "title": "Alfresco Enterprise Servlet Dashboard",
 "description": "Alfresco Enterprise Servlet monitoring using micrometer metrics",
 "tags": [
  "alfresco",
  "content-repository",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Alfresco servlet requests per Method (1h)",
   "type": "piechart",
   "description": "Alfresco servlet requests broken down by HTTP method (Past hour accumulation)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (increase(servlet_request_seconds_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alfresco servlet requests processing time per Method (1h)",
   "type": "piechart",
   "description": "Alfresco servlet requests processing time broken down by HTTP method (Past hour accumulation)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(servlet_request_seconds_sum[1h])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Alfresco Enterprise Servlet response heatmap",
   "type": "heatmap",
   "description": "Cumulative bucketed response time for servlet requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (servlet_request_seconds_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Alfresco Enterprise concurrent requests per context",
   "type": "timeseries",
   "description": "Alfresco Enterprise concurrent requests per context (stacked)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (context) (servlet_request_concurrent_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}