{
 "title": "Alfresco Enterprise REST API Dashboard",
 "description": "Report on Alfresco repository REST API performance",
 "tags": [
  "alfresco",
  "content-repository",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "REST API requests rate by HTTP method",
   "type": "timeseries",
   "description": "API Requests rate  by HTTP method",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (httpMethod) (rate(restapi_execution_time_seconds_count{alfresco_rest_api_endpoint!=\"probes\"}[1m]))",
     "legendFormat": "{{httpMethod}} requests rate"
    }
   ]
  },
  {
   "title": "REST API requests rate per repository",
   "type": "timeseries",
   "description": "REST API requests rate per repository",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(restapi_execution_time_seconds_count{alfresco_rest_api_endpoint!=\"probes\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "REST API requests average processing time by endpoint",
   "type": "timeseries",
   "description": "How much time (ms) are REST API endpoints taking to process requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (alfresco_rest_api_endpoint,alfresco_rest_api_model,alfresco_rest_api_version) (increase(restapi_execution_time_seconds_sum{alfresco_rest_api_endpoint!=\"probes\"}[3m])*1000)/sum by (alfresco_rest_api_endpoint,alfresco_rest_api_model,alfresco_rest_api_version) (increase(restapi_execution_time_seconds_count{alfresco_rest_api_endpoint!=\"probes\"}[3m]))",
     "legendFormat": "processing time - /{{alfresco_rest_api_model}}/versions/{{alfresco_rest_api_version}}/{{alfresco_rest_api_endpoint}}"
    }
   ]
  },
  {
   "title": "REST API average requests time per repository",
   "type": "timeseries",
   "description": "number of milliseconds the average REST API takes on each repository node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(restapi_execution_time_seconds_sum{alfresco_rest_api_endpoint!=\"probes\"}[1m])*1000) /sum by (instance) (increase(restapi_execution_time_seconds_count{alfresco_rest_api_endpoint!=\"probes\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 5 time consuming API requests (granularity endpoint)",
   "type": "timeseries",
   "description": "Top 5 time consuming API requests (granularity endpoint)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, restapi_execution_time_seconds_sum{alfresco_rest_api_endpoint!=\"probes\"})",
     "legendFormat": "/{{alfresco_rest_api_model}}/versions/{{alfresco_rest_api_version}}/{{alfresco_rest_api_endpoint}} (on {{instance}})"
    }
   ]
  },
  {
   "title": "Top 5 most executed API requests (endpoint granularity)",
   "type": "timeseries",
   "description": "The TOP 5 API endpoint which receive most queries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, restapi_execution_time_seconds_count{alfresco_rest_api_endpoint!=\"probes\"})",
     "legendFormat": "/{{alfresco_rest_api_model}}/versions/{{alfresco_rest_api_version}}/{{alfresco_rest_api_endpoint}} (on {{instance}})"
    }
   ]
  }
 ]
}