{
 "title": "AlfrescoDBDash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "active connection gauge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_connections_active" }
   ]
  },
  {
   "title": "Idle connections gauge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_connections_idle" }
   ]
  },
  {
   "title": "All query count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "queries_execution_time_seconds_count"
    }
   ]
  },
  {
   "title": "All query time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "queries_execution_time_seconds_sum"
    }
   ]
  },
  {
   "title": "Rate query count by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queries_execution_time_seconds_count{queryType='select'}[10s]))",
     "legendFormat": "Rate sum select"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_count{queryType='insert'}[10s]))",
     "legendFormat": "Rate sum insert"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_count{queryType='update'}[10s]))",
     "legendFormat": "Rate sum update"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_count{queryType='delete'}[10s]))",
     "legendFormat": "Rate sum delete"
    }
   ]
  },
  {
   "title": "Rate query time by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queries_execution_time_seconds_sum{queryType='select'}[10s]))",
     "legendFormat": "Rate sum select"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_sum{queryType='insert'}[10s]))",
     "legendFormat": "Rate sum insert"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_sum{queryType='update'}[10s]))",
     "legendFormat": "Rate sum update"
    },
    {
     "expr": "sum(rate(queries_execution_time_seconds_sum{queryType='delete'}[10s]))",
     "legendFormat": "Rate sum delete"
    }
   ]
  },
  {
   "title": "top 5 most Total count exec queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, queries_execution_time_seconds_count)"
    }
   ]
  },
  {
   "title": "top 5 most Total Time exec queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, queries_execution_time_seconds_sum)"
    }
   ]
  },
  {
   "title": "top 5 most Rate 10s count exec queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(queries_execution_time_seconds_count[10s]))"
    }
   ]
  },
  {
   "title": "top 5 most Rate 10s Time exec queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(queries_execution_time_seconds_sum[10s]))"
    }
   ]
  }
 ]
}