{
 "title": "Alfresco Enterprise Database Dashboard",
 "description": "Report on Alfresco repository database perfomance",
 "tags": [
  "alfresco",
  "content-repository",
  "sql"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active SQL connections",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(num_connections_active)", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Idle SQL connections",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(num_connections_idle)", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Top 5 most executed SQL queries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (statementID) (queries_execution_time_seconds_count))",
     "legendFormat": "{{statementID}}"
    }
   ]
  },
  {
   "title": "Top 5 time consuming SQL queries",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (statementID) (queries_execution_time_seconds_sum))",
     "legendFormat": "{{statementID}}"
    }
   ]
  },
  {
   "title": "SQL queries rate by query type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (queryType) (rate(queries_execution_time_seconds_count[1m]))",
     "legendFormat": "{{queryType}}"
    }
   ]
  },
  {
   "title": "Average query latency by query type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (queryType) (increase(queries_execution_time_seconds_sum[1m])*1000)/sum by (queryType) (increase(queries_execution_time_seconds_count[1m]))",
     "legendFormat": "{{queryType}}"
    }
   ]
  },
  {
   "title": "SQL queries average latency by statement ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (statementID) (increase(queries_execution_time_seconds_sum[1m])*1000)/sum by (statementID) (increase(queries_execution_time_seconds_count[1m]))",
     "legendFormat": "{{statementID}}"
    }
   ]
  },
  {
   "title": "SQL queries rate by statement ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (statementID) (rate(queries_execution_time_seconds_count[1m]))",
     "legendFormat": "{{statementID}}"
    }
   ]
  }
 ]
}