{
 "title": "AlfrescoRESTAPIDash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restapi_execution_time_seconds_count"
    }
   ]
  },
  {
   "title": "All requests time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "restapi_execution_time_seconds_sum"
    }
   ]
  },
  {
   "title": "Rate requests count by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(restapi_execution_time_seconds_count{httpMethod='GET'}[10s]))",
     "legendFormat": "Rate sum select"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_count{httpMethod='POST'}[10s]))",
     "legendFormat": "Rate sum insert"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_count{httpMethod='DELETE'}[10s]))",
     "legendFormat": "Rate sum update"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_count{httpMethod='PUT'}[10s]))",
     "legendFormat": "Rate sum delete"
    }
   ]
  },
  {
   "title": "Rate requests time by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(restapi_execution_time_seconds_sum{httpMethod='GET'}[10s]))",
     "legendFormat": "Rate sum select"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_sum{httpMethod='PUT'}[10s]))",
     "legendFormat": "Rate sum insert"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_sum{httpMethod='DELETE'}[10s]))",
     "legendFormat": "Rate sum update"
    },
    {
     "expr": "sum(rate(restapi_execution_time_seconds_sum{httpMethod='POST'}[10s]))",
     "legendFormat": "Rate sum delete"
    }
   ]
  },
  {
   "title": "top 5 most Total count exec restapi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, restapi_execution_time_seconds_count)"
    }
   ]
  },
  {
   "title": "top 5 most Total Time exec restapi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, restapi_execution_time_seconds_sum)"
    }
   ]
  },
  {
   "title": "top 5 most Rate 10s count exec restapi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(restapi_execution_time_seconds_count[10s]))"
    }
   ]
  },
  {
   "title": "top 5 most Rate 10s Time exec restapi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(restapi_execution_time_seconds_sum[10s]))"
    }
   ]
  }
 ]
}