env:
  global:
    # Release version has to start with real version (23.2.0-....) for the docker image to build successfully.
    - RELEASE_VERSION=25.5.0
    - DEVELOPMENT_VERSION=25.6.0-A.1-SNAPSHOT
