#BUIDING CONTAINER FOR TAS TESTING WITH DIFFERENT DATABASES

FROM alfresco/alfresco-content-repository:latest

ADD https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar /usr/local/tomcat/lib/mysql-connector-java-8.0.30.jar
