version: "3"

services:
    alfresco:
        image: alfresco/alfresco-content-repository:${ALFRESCO_TAG}
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                "
        ports:
            - 8082:8080 #Browser port

    alfresco-pdf-renderer:
        image: alfresco/alfresco-docker-alfresco-pdf-renderer:${TRANSFORMERS_TAG}
        ports:
            - 8090:8090

    imagemagick:
        image: alfresco/alfresco-docker-imagemagick:${TRANSFORMERS_TAG}
        ports:
            - 8091:8090

    libreoffice:
        image: alfresco/alfresco-docker-libreoffice:${TRANSFORMERS_TAG}
        ports:
            - 8092:8090

    share:
        image: alfresco/alfresco-share:${SHARE_TAG}
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
        ports:
            - 8080:8080

    postgres:
        image: postgres:${POSTGRES_TAG}
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:${SOLR6_TAG}
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        ports:
            - 8083:8983 #Browser port
