name: ACS Packaging CI

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: Alfresco/acs-packaging/.github/workflows/ci.yml@master
    with:
      java-version: "17"
      alf-licence-s3-path: s3://acs-license/acs/alf25-allenabled.lic
      dtas-version: v1.9.0
      distribution-zip-java-versions: "[17, 21]"
      pipeline-java-versions: '["DEFAULT", 21]'
    secrets: inherit
