name: ACS Packaging CI

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
  workflow_call:
  workflow_dispatch:

env:
  JAVA_VERSION: "21"
  AZURE_AUTHENTICATION_MODE: sharedKey
  AZURE_STORAGE_ACCOUNT_NAME: acspackagingci
  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_PACKAGING_STORAGE_ACCOUNT_KEY }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  GIT_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  CI_WORKSPACE: ${{ github.workspace }}
  AWS_REGION: eu-west-1
  TAS_ENVIRONMENT: ./tests/environment
  TAS_SCRIPTS: ../alfresco-community-repo/packaging/tests/scripts
  ALF_LICENCE_S3_PATH: s3://acs-license/acs/alf26-allenabled.lic
  ALF_LICENCE_LOCAL_PATH: /tmp/licence.lic
  PYTHON_VERSION: 3.8.12
  DTAS_VERSION: v1.7.3

jobs:
  tas_test_with_mtls:
    name: ${{ matrix.testSuite }} TAS tests with mutal TLS
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '[skip mtls]') &&
      !contains(github.event.head_commit.message, '[skip tests]')
    strategy:
      fail-fast: false
      matrix:
        include:
          - testSuite: Solr Mutual TLS
            pom-dir: tests/tas-mtls
            profiles: run-mtls-solr
            compose-file: docker-compose-solr-mtls.yml
            mtls: true
            disabledHostnameVerification: false
            deploy-timeout: 10
          - testSuite: Solr Mutual TLS Disabled Hostname Verification
            pom-dir: tests/tas-mtls
            profiles: run-mtls-solr
            compose-file: docker-compose-solr-mtls.yml
            mtls: true
            disabledHostnameVerification: true
            deploy-timeout: 10
          - testSuite: Elasticsearch Mutual TLS
            pom-dir: tests/tas-mtls
            profiles: run-mtls-elasticsearch
            compose-file: docker-compose-elasticsearch-mtls.yml
            mtls: true
            disabledHostnameVerification: false
            deploy-timeout: 10
          - testSuite: Elasticsearch Mutual TLS Disabled Hostname Verification
            pom-dir: tests/tas-mtls
            profiles: run-mtls-elasticsearch
            compose-file: docker-compose-elasticsearch-mtls.yml
            mtls: true
            disabledHostnameVerification: true
            deploy-timeout: 10
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v12.4.3
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v12.4.3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v12.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: "Generate Keystores and Truststores for Mutual TLS configuration"
        if: ${{ matrix.mtls }}
        run: |
          git clone -b "feature/ACS-7965-elasticsearch-mtls" --depth=1 "https://${{ secrets.BOT_GITHUB_USERNAME }}:${{ secrets.BOT_GITHUB_TOKEN }}@github.com/Alfresco/alfresco-ssl-generator.git"
          if ${{ matrix.disabledHostnameVerification }} ; then
            bash ${{ env.CI_WORKSPACE }}/alfresco-ssl-generator/scripts/ci/generate_keystores_wrong_hostnames.sh
            echo "HOSTNAME_VERIFICATION_DISABLED=true" >> "$GITHUB_ENV"
          else
            bash ${{ env.CI_WORKSPACE }}/alfresco-ssl-generator/scripts/ci/generate_keystores.sh
            echo "HOSTNAME_VERIFICATION_DISABLED=false" >> "$GITHUB_ENV"
          fi
          bash ${{ env.CI_WORKSPACE }}/alfresco-ssl-generator/scripts/ci/convert_testclient_keystore_to_pem.sh "${{ env.CI_WORKSPACE }}"
      - name: "List generated keystores"
        if: ${{ matrix.mtls }}
        run: find ${{ env.CI_WORKSPACE }}/keystores -type f -exec ls -la {} + || echo "No keystores directory found"
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: |
          bash ./scripts/ci/init.sh
          bash ./scripts/ci/build.sh
      - name: "Set up the environment"
        run: |
          ${{ env.TAS_SCRIPTS }}/start-compose.sh ${{ env.TAS_ENVIRONMENT }}/${{ matrix.compose-file }}
          ${{ env.TAS_SCRIPTS }}/wait-for-alfresco-start.sh "https://localhost:8443/alfresco"
      - name: "Show all container statuses"
        if: ${{ always() }}
        run: docker ps -a
      - name: "Dump Elasticsearch container logs"
        if: ${{ always() }}
        run: docker logs --tail 500 elasticsearch || echo "No elasticsearch container found"
      - name: "Dump Live Indexing container logs"
        if: ${{ always() }}
        run: docker logs --tail 500 live-indexing || echo "No live-indexing container found"
      - name: "Run tests"
        id: tests
        timeout-minutes: ${{ matrix.deploy-timeout }}
        run: mvn -B install -ntp -f ${{ matrix.pom-dir }}/pom.xml -P${{ matrix.profiles }} -Denvironment=default -DrunBugs=false -Dmessaging.broker.username=admin -Dmessaging.broker.password=admin # pragma: allowlist secret
      - name: "Print output after failure"
        if: ${{ always() && steps.tests.outcome == 'failure' }}
        run: ${TAS_SCRIPTS}/output_logs_for_failures.sh "${{ matrix.pom-dir }}"
      - name: "Clean Maven cache"
        run: bash ./scripts/ci/cleanup_cache.sh
