name: Hackathon

on:
  push:

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set timestamp
        run: |
          echo "TIMESTAMP=$(date +%s)" >> ${GITHUB_ENV}
      - name: perform build
        run: sleep 120
      - name: create report
        run: |
          mkdir reports && echo '{"build": "testBuild","commitId": "123456","artifacts": [{"name": "alfresco.war","sha1": "123456"}]}' > reports/report-${{ github.event.repository.name }}-${{ github.ref_name }}-${{ env.TIMESTAMP }}.json
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-report.json
          path: reports/report-${{ github.event.repository.name }}-${{ github.ref_name }}-${{ env.TIMESTAMP }}.json
