name: Master/Release branch workflow

on:
  push:
    branches:
      - master
      - release/**

env:
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  GIT_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60


jobs:
  run_ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  docker_latest:
    name: "Update latest and Single Pipeline <acs>-<build> images"
    runs-on: ubuntu-latest
    needs: [run_ci]
    if: >
      always() &&
      (needs.run_ci.result == 'skipped' || needs.run_ci.result == 'success') &&
      (! contains(github.event.head_commit.message, '[skip docker_latest]')) &&
      github.ref_name == 'master' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/acs-community-packaging/.github/actions/get-build-info@feature/ACS-3844_migrate-to-GHA
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.25.0
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: |
          bash ./scripts/ci/init.sh
          bash ./scripts/ci/build.sh
      - name: "Update images"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn -B -V clean install -ntp -DskipTests -Dmaven.javadoc.skip=true -Dbuild-number=${BUILD_NUMBER} -Pags -Ppush-docker-images,pipeline

  docker_release:
    name: "Update latest and Single Pipeline <acs>-<build> images"
    runs-on: ubuntu-latest
    needs: [run_ci]
    if: >
      always() &&
      (needs.run_ci.result == 'skipped' || needs.run_ci.result == 'success') &&
      (! contains(github.event.head_commit.message, '[skip docker_release]')) &&
      contains(github.ref_name, 'release/') && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/acs-community-packaging/.github/actions/get-build-info@feature/ACS-3844_migrate-to-GHA
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.25.0
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: |
          bash ./scripts/ci/init.sh
          bash ./scripts/ci/build.sh
      - name: "Update images"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn -B -V clean install -ntp -DskipTests -Dmaven.javadoc.skip=true -Dbuild-number=${BUILD_NUMBER} -Ppush-docker-images,pipeline,release-branch